#!/bin/bash

cp $OPENSHIFT_DATA_DIR/local.xml $OPENSHIFT_REPO_DIR/app/etc
mv $OPENSHIFT_REPO_DIR/.htaccess.sample $OPENSHIFT_REPO_DIR/.htaccess
rm -rf $OPENSHIFT_REPO_DIR/media
mv -R $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/media