<?php
    if(!Mage::getSingleton('customer/session')->isLoggedIn()) {
        return;
    }
    $_collection = $this->getCustomerRegistries();
    $helper = Mage::helper('a2_giftregistry');
    $productId = $this->getRequest()->getParam('id');
?>
<div class="block-content">
    <?php if(!$_collection->count()): ?>
        <div>Add a <a href="/giftregistry/index/index">Gift Registry!</a></div>
    <?php else: ?>
        <ul>
            <?php $count = 0; ?>
            <?php foreach($_collection as $registry): ?>
                <li>
                    <label>
                        <?php if($helper->isItemInRegistry($productId, $registry->getEntityId())): ?>
                            <?php 
                                $count++;
                                $params = array(
                                    '_query' => array(
                                        'registry_id' => $registry->getEntityId(),
                                    )
                                );
                            ?>                        
                            Product is in <b><a href="<?php echo Mage::getUrl('giftregistry/view/view', $params); ?>"><?php echo $registry->getEventName(); ?></b></a> Gift Registry
                        <?php else: ?>
                            <input type="checkbox" <?php echo $registry->getId(); ?> data-product-id="<?php echo $productId ?>" name="registry_id" data-id="<?php echo $registry->getEntityId(); ?>" />&nbsp;<?php echo $registry->getEventName(); ?>                            
                        <?php endif; ?>
                    </label>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php if($_collection->count() !== $count): ?>
            <button class="button js-add-to-gift-registry"><?php echo $this->__('Add to gift registry') ?></button>
        <?php endif; ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    (function() {
        var addToGiftRegistryBtn = document.querySelector('.js-add-to-gift-registry');

        addToGiftRegistryBtn.addEventListener('click', function(event){
            event.preventDefault();
            var checkedRegistry = document.querySelectorAll('input[name="registry_id"]:checked');
            var registryIds = [];
            for(var index = 0, len = checkedRegistry.length; index < len; index+=1) {
                registryIds.push(checkedRegistry[index].getAttribute('data-id'));
            }
            if(!checkedRegistry.length) return;
            new Ajax.Request('/giftregistry/index/newItem', {
                method: 'post',
                parameters: {
                    registry_id: registryIds.join(','),
                    product_id: checkedRegistry[0].getAttribute('data-product-id')
                },
                onSuccess: function(response) {
                    if(response.status == 200) {
                        window.location.reload();
                    }
                }
            });
        });
    }());

</script>