<?php
    $_collection = $this->getCustomerRegistries();
    $helper = Mage::helper('a2_giftregistry');
?>
<div class="customer-list">
    <?php if(!$_collection->count()): ?>
        <h2><?php echo $this->__('You have no registries.') ?></h2>
    <?php else: ?>
        <ul>
            <?php foreach($_collection as $registry): ?>
                <li>
                    <h3><?php echo $registry->getEventName(); ?></h3>
                    <p><?php echo $this->__('Event Location:') ?> <?php echo $registry->getEventLocation(); ?></p>
                    <p><?php echo $this->__('Event Country:') ?> <?php echo $registry->getEventCountry(); ?></p>                    
                    <p><?php echo $this->__('Event Date:') ?> <?php echo $registry->getEventDate(); ?></p>
                    <a href="<?php echo $this->getUrl('giftregistry/view/view', array('_query' => array('registry_id' => $registry->getEntityId()))) ?>">
                        <?php echo $this->__('View Registry') ?>
                    </a>
                    <?php if($helper->isRegistryOwner($registry->getCustomerId())): ?>
                        <a href="<?php echo $this->getUrl('giftregistry/index/edit', array('_query' => array('registry_id' => $registry->getEntityId()))) ?>">
                            <?php echo $this->__('Edit Registry') ?>
                        </a>
                        <a href="<?php echo $this->getUrl('giftregistry/index/delete', array('_query' => array('registry_id' => $registry->getEntityId()))) ?>">
                            <?php echo $this->__('Delete Registry') ?>
                        </a>
                    <?php endif; ?>
                </li>
                <li><br></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <a href="<?php echo $this->getUrl('giftregistry/index/new') ?>">
        <?php echo $this->__('Click Here to create a new Gift Registry') ?>
    </a>    
</div>
