<?php $registry = Mage::registry('loaded_registry'); ?>
<?php 
    $customerId = $registry->getCustomerId();
    $customer = Mage::getModel('customer/customer')
        ->load($customerId);
    $customerName = $customer->getFirstname() . ' ' . $customer->getLastname();
?>
<h3 style="color:#ff0000;"><?php echo $customerName ?></h3>
<h3><?php echo $registry->getEventName(); ?></h3>
<p><strong><?php echo $this->__('Event Date:') ?> <?php echo $registry->getEventDate(); ?></strong></p>
<p><strong><?php echo $this->__('Event Location:') ?> <?php echo $registry->getEventLocation(); ?></strong></p>