<?php if($this->getIsEnabled()): ?>
<!-- mageinnSlider -->
<?php if($this->getFromPrice() != $this->getToPrice()): ?>
<dt><?php echo $this->__('Price') ?></dt>
<dd><div id="mageinnSliderWrap"><div id="mageinnSlider"></div><div id="msFrom"></div><div id="msTo"></div></div>
<script type="text/javascript">
//<![CDATA[
var pricePattern  = '<?php echo $this->getCurrencyPattern(); ?>';
var slider = document.getElementById('mageinnSlider');
var priceLabels = [
        document.getElementById('msFrom'),
        document.getElementById('msTo')
];
noUiSlider.create(slider, {
	start: [<?php echo $this->getCurrFromPrice(); ?>, <?php echo $this->getCurrToPrice(); ?>],
        <?php if($this->getStep()): ?>
        step: <?php echo $this->getStep(); ?>,
        <?php endif; ?>
	connect: true,
	range: {
		'min': <?php echo $this->getFromPrice(); ?>,
		'max': <?php echo $this->getToPrice(); ?>
        
	},
        //tooltips: [ wNumb({ decimals: 2 }), wNumb({ decimals: 2 }) ],
        format: wNumb({
                decimals: 2,
		thousand: '.'
	})
});
slider.noUiSlider.on('update', function( values, handle ) {
    priceLabels[handle].innerHTML = pricePattern.replace('123',values[handle]);
});
slider.noUiSlider.on('set', function( values, handle ){
    msAjax(prepareMsUrl(values[0],values[1]), true);
});
//]]>
</script></dd>
<?php endif; ?>
<?php endif; ?>